openapi: 3.0.3
info:
  description: This is an OpenAPI definition file which contains violations of the rule 'Underscores (_) should not be used in URIs' created by experts.
  version: 0.1.0
  title: Example OpenAPI Definition File
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api.example.com:8443/v1
    description: Sandbox server (uses test data)
paths:
  # Justus + Sebastian + Ana Franco da Silva + Oliver Kopp (+1 violation)
  /user_names:
    get:
      tags:
        - user management
      description: Returns a list of all user names 
      summary: Return user names
      responses:
        200:
          description: Array of user name objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserName"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Justus (+1 violation)
  /user_names/{userId}:
    delete:
      tags:
        - user management
      description: Deletes the full name of a user identified via ID
      summary: Delete user name
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: Successfully deleted user name object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Sebastian (+1 violation)
  /users/{userId}/cvs/place_of_birth:
    get:
      tags:
        - user management
      description: Returns the details from the cv of the birthplace of a user identified by ID
      summary: Get the birthplace from a user
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      responses:
        200:
          description: User object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Timo Pfaff + Maik Betka (+1 violation)
  /users/{userId}/invoices/power_consumption_invoice:
    post:
      tags:
        - user management
      description: Creates power cosumption invoice of a user that is identified by an ID
      summary: Create power cosumption invoice
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            minimum: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Invoice"
      responses:
        200:
          description: Power consumption PDF file
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
  # Eigene (+1 violation)
  /_user:
    get:
      tags:
        - user management
      description: Returns a list of all user names 
      summary: Return user names
      responses:
        200:
          description: Array of user name objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserName"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponse"
components:
  schemas:
    UserName:
      description: A user name object
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
    User:
      description: A user of the system
      type: object
      properties:
        userId:
          type: number
        userName:
          type: string
        birthplace:
          type: string
        email:
          type: string
    Invoice:
      description: An invoice
      type: object
      properties:
        invoiceId:
          type: number
        paymentMethod:
          type: string
        currency:
          type: string
        amount:
          type: number
    GenericResponse:
      description: A generic response object with a message attribute
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
security:
  - BasicAuth: []
