{
    "openapi": "3.0.0",
    "servers": [
        {
            "url": "https://api.shop-pro.jp"
        }
    ],
    "info": {
        "contact": {
            "name": "\u304a\u554f\u3044\u5408\u305b\u7a93\u53e3",
            "url": "https://shop-pro.jp/?mode=inq"
        },
        "description": "# \u30ab\u30e9\u30fc\u30df\u30fc\u30b7\u30e7\u30c3\u30d7\u30a2\u30d7\u30ea\u30b9\u30c8\u30a2 API\n\n[\u30a2\u30d7\u30ea\u30b9\u30c8\u30a2](https://app.shop-pro.jp/)\u306b\u3066\u516c\u958b\u3059\u308b\u30a2\u30d7\u30ea\u306b\u5bfe\u3057\u3066\u3001\u4e00\u822c\u516c\u958b\u3057\u3066\u3044\u308b[\u30ab\u30e9\u30fc\u30df\u30fc\u30b7\u30e7\u30c3\u30d7API](https://developer.shop-pro.jp/docs/colorme-api)\u306b\u52a0\u3048\u3066\u3001\u30ab\u30e9\u30fc\u30df\u30fc\u30b7\u30e7\[...]",
        "termsOfService": "https://api.shop-pro.jp/developers/tos",
        "title": "\u30ab\u30e9\u30fc\u30df\u30fc\u30b7\u30e7\u30c3\u30d7\u30a2\u30d7\u30ea\u30b9\u30c8\u30a2 API",
        "version": "1.0.0",
        "x-apisguru-categories": [
            "ecommerce"
        ],
        "x-description-language": "jp",
        "x-logo": {
            "url": "https://api.apis.guru/v2/cache/logo/https_static-www.shop-pro.jp_img_cms_components_cms_header_cms_header_brand.svg"
        },
        "x-origin": [
            {
                "format": "swagger",
                "url": "https://api.shop-pro.jp/appstore//v1/open_api.json",
                "version": "2.0"
            }
        ],
        "x-providerName": "shop-pro.jp"
    },
    "tags": [
        {
            "name": "application_charge",
            "x-displayName": "\u8ab2\u91d1"
        },
        {
            "description": "\u30b7\u30e7\u30c3\u30d7\u30da\u30fc\u30b8\u306b\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u3092\u633f\u5165\u3059\u308bAPI\u3067\u3059\u3002\n\n\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u30a8\u30f3\u30c9\u30dd\u30a4\u30f3\u30c8\u3092\u5229\u7528\u3059\u308b\u5834\u5408\u3001\u4ee5\u4e0b\u306e\u70b9\u306b\u3054\u6ce8\u610f\u304f\u3060\u3055\u3044\u3002\n- \u30b9\u30af\u30ea\u30d7\u30c8\u3092\u914d\u4fe1\u3059\u308b\u30b5\u30fc\u30d0\u306f\u3001\u9069\u5207\u306aCORS\[...]",
            "name": "script",
            "x-displayName": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0"
        },
        {
            "description": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u3092\u633f\u5165\u3059\u308bAPI\u3067\u3059\u3002\u203b\u65b0\u898f\u30c7\u30d9\u30ed\u30c3\u30d1\u30fc\u306f\u3053\u306e\u30a8\u30f3\u30c9\u30dd\u30a4\u30f3\u30c8\u3092\u5229\u7528\u3067\u304d\u307e\u305b\u3093\u3002\u4ee3\u308f\u308a\u306b [\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0](/open_api#tag/script) \u3092\u3054\u5229\u7528\u304f\u3060\u3055\u3044",
            "name": "script(deprecated)",
            "x-displayName": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0(deprecated)"
        },
        {
            "description": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u3092\u633f\u5165\u3059\u308bAPI\u3067\u3059\u3002\u203b\u65b0\u898f\u30c7\u30d9\u30ed\u30c3\u30d1\u30fc\u306f\u3053\u306e\u30a8\u30f3\u30c9\u30dd\u30a4\u30f3\u30c8\u3092\u5229\u7528\u3067\u304d\u307e\u305b\u3093",
            "name": "inline_script",
            "x-displayName": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8(deprecated)"
        },
        {
            "description": "\u30a2\u30d7\u30ea\u3092\u30a2\u30f3\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3059\u308bAPI\u3067\u3059\u3002",
            "name": "uninstallation",
            "x-displayName": "\u30a2\u30f3\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb"
        }
    ],
    "paths": {
        "/appstore/v1/application_charges.json": {
            "post": {
                "description": "\u300c\u30a2\u30d7\u30ea\u5185\u8ab2\u91d1\u300d\u306f\u3059\u3067\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6e08\u307f\u306e\u30a2\u30d7\u30ea\u4e0a\u306b\u304a\u3044\u3066\u3001\u5229\u7528\u8005\u304c\u8ffd\u52a0\u306e\u8cb7\u3044\u5207\u308a\u306b\u3088\u308b\u8ab2\u91d1\u306b\u3088\u3063\u3066\u65b0\u305f\u306a\u30a2\u30d7\u30ea\u5185\u306e\u6a5f\u80fd\u3092\u63d0\u4f9b\u3055\u308c\u308b\u5834\u5408\u306a\u3069\u306b\u3001\u5229\u7528\u8005\u3078\u8cb7\u3044[...]",
                "operationId": "postApplicationCharge",
                "security": [
                    {
                        "OAuth2": [
                            "write_application_charge"
                        ]
                    }
                ],
                "summary": "\u30a2\u30d7\u30ea\u5185\u8ab2\u91d1\u30c7\u30fc\u30bf\u306e\u4f5c\u6210",
                "tags": [
                    "application_charge"
                ]
            }
        },
        "/appstore/v1/installation.json": {
            "delete": {
                "description": "\u3053\u306eAPI\u306f OAuth \u306e\u30a2\u30af\u30bb\u30b9\u30c8\u30fc\u30af\u30f3\u306b\u7d10\u4ed8\u304f\u30a2\u30d7\u30ea\u30b1\u30fc\u30b7\u30e7\u30f3\u3092\u30b7\u30e7\u30c3\u30d7\u304b\u3089\u524a\u9664\u3057\u307e\u3059\u3002\n\u3053\u306eAPI\u3092\u5229\u7528\u3057\u305f\u5834\u5408\u3001\u30b7\u30e7\u30c3\u30d7\u30aa\u30fc\u30ca\u30fc\u304c\u30a2\u30f3\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u305f\u5834\u5408\u3068\u7570\u306a\u308a\u3001\u30a2\u30f3\u3[...]",
                "operationId": "deleteInstallation",
                "security": [
                    {
                        "OAuth2": []
                    }
                ],
                "summary": "\u30a2\u30d7\u30ea\u30b9\u30c8\u30a2\u30a2\u30d7\u30ea\u306e\u30a2\u30f3\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb",
                "tags": [
                    "uninstallation"
                ]
            }
        },
        "/appstore/v1/recurring_application_charges/{recurringApplicationChargeId}/usage_charges.json": {
            "post": {
                "description": "\u30a2\u30d7\u30ea\u5185\u3067\u57fa\u672c\u6a5f\u80fd\u304c\u5229\u7528\u3055\u308c\u305f\u983b\u5ea6\u306b\u4f34\u3063\u3066\u6bce\u6708\u306e\u8acb\u6c42\u304c\u5909\u52d5\u3059\u308b\u3088\u3046\u306a\u30a2\u30d7\u30ea\u306e\u5834\u5408\u306f\u300c\u5f93\u91cf\u8ab2\u91d1\u300d\u3092\u4f7f\u3063\u3066\u5229\u7528\u8005\u306b\u5909\u52d5\u5206\u306e\u8acb\u6c42\u3092\u884c\u3046\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002\n\u203b\u7121\u6599\u304a\u8a66\u30[...]",
                "operationId": "createUsageCharge",
                "security": [
                    {
                        "OAuth2": [
                            "write_application_charge"
                        ]
                    }
                ],
                "summary": "\u5f93\u91cf\u8ab2\u91d1\u30c7\u30fc\u30bf\u306e\u4f5c\u6210",
                "tags": [
                    "application_charge"
                ]
            }
        },
        "/appstore/v1/script_tags.json": {
            "get": {
                "description": "",
                "operationId": "getShopScriptTags",
                "security": [
                    {
                        "OAuth2": [
                            "read_shop_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                "tags": [
                    "script"
                ]
            },
            "post": {
                "description": "",
                "operationId": "createShopScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_shop_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u4f5c\u6210",
                "tags": [
                    "script"
                ]
            }
        },
        "/appstore/v1/script_tags/{scriptTagId}.json": {
            "delete": {
                "description": "",
                "operationId": "deleteScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_shop_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u524a\u9664",
                "tags": [
                    "script"
                ]
            },
            "get": {
                "description": "",
                "operationId": "getShopScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "read_shop_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                "tags": [
                    "script"
                ]
            },
            "put": {
                "description": "",
                "operationId": "updateShopScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_shop_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u66f4\u65b0",
                "tags": [
                    "script"
                ]
            }
        },
        "/v1/inline_script_tags.json": {
            "get": {
                "description": "",
                "operationId": "getInlineScriptTags",
                "security": [
                    {
                        "OAuth2": [
                            "read_inline_script_tags"
                        ]
                    }
                ],
                "summary": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                "tags": [
                    "inline_script"
                ]
            },
            "post": {
                "description": "",
                "operationId": "createInlineScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_inline_script_tags"
                        ]
                    }
                ],
                "summary": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u767b\u9332",
                "tags": [
                    "inline_script"
                ]
            }
        },
        "/v1/inline_script_tags/{inlineScriptTagId}.json": {
            "delete": {
                "description": "",
                "operationId": "deleteInlineScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_inline_script_tags"
                        ]
                    }
                ],
                "summary": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u524a\u9664",
                "tags": [
                    "inline_script"
                ]
            },
            "get": {
                "description": "",
                "operationId": "getInlineScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "read_inline_script_tags"
                        ]
                    }
                ],
                "summary": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                "tags": [
                    "inline_script"
                ]
            },
            "put": {
                "description": "",
                "operationId": "updateInlineScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_inline_script_tags"
                        ]
                    }
                ],
                "summary": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u66f4\u65b0",
                "tags": [
                    "inline_script"
                ]
            }
        },
        "/v1/script_tags.json": {
            "get": {
                "description": "",
                "operationId": "getScriptTags",
                "security": [
                    {
                        "OAuth2": [
                            "read_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                "tags": [
                    "script(deprecated)"
                ]
            },
            "post": {
                "description": "",
                "operationId": "createScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u4f5c\u6210",
                "tags": [
                    "script(deprecated)"
                ]
            }
        },
        "/v1/script_tags/{scriptTagId}.json": {
            "delete": {
                "description": "",
                "security": [
                    {
                        "OAuth2": [
                            "write_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u524a\u9664",
                "tags": [
                    "script(deprecated)"
                ]
            },
            "get": {
                "description": "",
                "operationId": "getScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "read_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                "tags": [
                    "script(deprecated)"
                ]
            },
            "put": {
                "description": "",
                "operationId": "updateScriptTag",
                "security": [
                    {
                        "OAuth2": [
                            "write_script_tags"
                        ]
                    }
                ],
                "summary": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u66f4\u65b0",
                "tags": [
                    "script(deprecated)"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "OAuth2": {
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://api.shop-pro.jp/oauth/authorize",
                        "scopes": {
                            "read_inline_script_tags": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                            "read_script_tags": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97(deprecated)",
                            "read_shop_script_tags": "\u30b7\u30e7\u30c3\u30d7\u30da\u30fc\u30b8\u3078\u306e\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u53d6\u5f97",
                            "write_application_charge": "\u8ab2\u91d1\u30c7\u30fc\u30bf\u3092\u4f5c\u6210",
                            "write_inline_script_tags": "\u30a4\u30f3\u30e9\u30a4\u30f3\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u767b\u9332",
                            "write_script_tags": "\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u767b\u9332(deprecated)",
                            "write_shop_script_tags": "\u30b7\u30e7\u30c3\u30d7\u30da\u30fc\u30b8\u3078\u306e\u30b9\u30af\u30ea\u30d7\u30c8\u30bf\u30b0\u306e\u767b\u9332"
                        },
                        "tokenUrl": "https://api.shop-pro.jp/oauth/token"
                    }
                },
                "type": "oauth2"
            }
        }
    }
}